# Generated by Django 4.2.9 on 2024-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('item_desc', models.CharField(default='Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi facilis saepe sit quaerat quos harum necessitatibus quod dolore ut alias quis nostrum illum, quasi aspernatur et in rerum rem reiciendis!', max_length=5000)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
