# Generated by Django 4.2.9 on 2024-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
