# Generated by Django 4.2.9 on 2024-01-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='prod_code',
            field=models.IntegerField(default=50),
        ),
    ]
