# Generated by Django 4.2.9 on 2024-01-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0003_item_added_by_item_prod_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='prod_pic.jpg', upload_to='products_pictures'),
        ),
    ]
