# Generated by Django 4.2.9 on 2024-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
    ]
