# Generated by Django 4.2.9 on 2024-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0006_item_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='features_prod',
            field=models.BooleanField(default=False),
        ),
    ]
