# Generated by Django 4.2.9 on 2024-02-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0008_item_rest_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rest_owner',
            new_name='company_owner',
        ),
    ]
