# Generated by Django 4.2.9 on 2024-02-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0010_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item',
            new_name='product',
        ),
    ]
