# Generated by Django 4.2.9 on 2024-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0013_checkout_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='last_name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
