# Generated by Django 4.2.9 on 2024-02-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0014_checkout_email_checkout_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
