# Generated by Django 4.2.9 on 2024-02-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0015_remove_checkout_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
