# Generated by Django 4.2.9 on 2024-03-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0018_alter_checkout_address_alter_checkout_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.TextField(max_length=255),
        ),
    ]
