# Generated by Django 4.2.9 on 2024-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0019_alter_checkout_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.TextField(),
        ),
    ]
